export const PROJECTS = [
  {
    slug: "1-hex-generator",
    title: "HEX Generator",
    description: "Crea un generador random de colores en fromato hexadecimal.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "2-rgb-generator",
    title: "RGB Generator",
    description: "Crea un generador random de colores en formato RGB.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "3-calculator",
    title: "Calculator",
    description: "Crea una calculadora básica con HTML, CSS y JS.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "4-crud-tasks",
    title: "To-Do list",
    description: "Crea un crud básico de tareas por hacer.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "5-letter-counter",
    title: "Letter counter",
    description: "Crea un contador de caracteres.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "6-count-down",
    title: "Count down",
    description: "Crea un temporizador básico.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "7-carousel",
    title: "Carousel",
    description: "Crea un carousel de imágenes básico.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "8-image-loading",
    title: "Image loading",
    description: "Crea un revelador de imágenes.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "9-pointer-move",
    title: "Pointer move",
    description: "Crea una sombra detras del puntero del mouse.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "10-grid-background",
    title: "Grid background",
    description: "Crea una imagen de fondo con formas de cuadrados.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "11-typing-effect",
    title: "Typing effect",
    description: "Efecto escritura.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "12-horizontal-scroll",
    title: "Horizontal scroll",
    description: "Scroll horizontal en lista de usuarios.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "13-bottom-sheet",
    title: "Bottom sheet",
    description:
      "Crea una hoja inferior, ventana que se levanta desde la parte inferior (Desktop - Mobile)",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "14-searching-text",
    title: "Searching text",
    description: "Busca palabras o partes de las mismas en un párrafo",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "15-background-video",
    title: "Background video",
    description: "Pon un video como background en tu web sin necesidad de js.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "16-send-button-animation",
    title: "Send button animation",
    description: "Animación sobre botón de enviar.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "17-infinity-scroll",
    title: "Infinity scroll",
    description: "Infinity scroll sobre una linea de cards.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "18-infinity-scroll-page",
    title: "Infinity scroll page",
    description: "Uso de infinity scroll en una web.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "19-infinity-scroll-page-2",
    title: "Infinity scroll page",
    description: "Uso de infinity scroll en una web.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "20-instagram-navbar",
    title: "Instagram navbar",
    description: "Clon de navbar usado en instagram.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "21-login-register-localstorage",
    title: "Login - register",
    description: "Login y registro usando local storage.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "22-theme-toggle",
    title: "Theme toggle",
    description: "Cambia entre tema dark, light o el definido en tu sistema.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "23-titles-observer",
    title: "Title observer",
    description:
      "Usa observers para saber en que sección de un texto está leyendo el usuario.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "24-otp-code-verification",
    title: "OTP code verification",
    description: "Página para verificación OTP.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "25-text-editor",
    title: "Text editor",
    description: "Crea un editor de texto básico.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "26-button-hover-effect",
    title: "Button hover effect",
    description: "Efecto sobre borde de boton al hacer hover sobre el.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "27-glassmorphsim-effect",
    title: "Glassmorphsim effect",
    description: "Efecto vidrio sobre card y hover.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "28-floating-menu",
    title: "Floating menu",
    description: "Menu flotanate animado.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "29-landing-page-kate",
    title: "Landing page Kate",
    description: "Landing page básica.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "30-landing-page-animals",
    title: "Landing page animals",
    description: "Landing page sobre animales. Efecto para cambio de imagen.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "31-quiz-app",
    title: "Quiz app",
    description: "Crea una página para realizar un quiz corto.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "32-basic-sidebar",
    title: "Basic sidebar",
    description: "Crea un sidebar básico colapsable.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "33-stacked-images",
    title: "Stacked images",
    description: "Listado de imágenes en pila.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "34-google-search-bar",
    title: "Google search bar",
    description: "Clon de la barra de búsqueda de google.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "35-card-conan",
    title: "Card",
    description: "Card con temática de Conan.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "36-landing-page-kfc",
    title: "Landing page de KFC",
    description: "Simulación de landing page para KFC.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "37-animated-menu",
    title: "Animated menu",
    description: "Menu animado para navegación.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "38-card-nike",
    title: "Card",
    description: "Card con temática de nike.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "39-landing-page-netflix",
    title: "Landing page de netflix",
    description: "Landing page de película de netflix.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "40-card-hover",
    title: "Card",
    description: "Card con efecto hover.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "41-animated-waves",
    title: "Animated waves",
    description: "Animación de footer con olas.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "42-music-card",
    title: "Music card",
    description: "Card para tema musical.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "43-card-hover-menu",
    title: "Card",
    description: "Card con efecto hover.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "44-toggle-theme",
    title: "Toggle theme",
    description: "Crea un switch para cambiar de tema en tu web.",
    learnings: ["HTML", "CSS"],
  },
  {
    slug: "45-shoes-mousehover",
    title: "Shoes mousehover",
    description: "Card con efecto mousehover.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "46-menu-mousehover",
    title: "Menu mousehover",
    description: "Menu con efecto mousehover para cambio de contenido.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "47-slider-video",
    title: "Slider video",
    description: "Crea un slider de videos.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "48-mouse-bear",
    title: "Mouse Bear",
    description: "Oso que sigue harra de miel.",
    learnings: ["HTML", "CSS", "JS"],
  },
  {
    slug: "49-keyboard-game",
    title: "Keyboard game",
    description: "Juego para practicar escritura con el teclado.",
    learnings: ["HTML", "CSS", "JS"],
  },
];
